---
dependency:
  enabled: false
driver:
  name: vagrant
  provider:
    name: virtualbox
platforms:
  - name: buster
    box: debian/buster64
    interfaces:
      - network_name: private_network
        auto_config: true
        ip: 172.16.100.12
        type: static
lint: |
  set -e
  yamllint -c .yamllint .
  ansible-lint --exclude molecule/ --exclude library/
  flake8 --exclude roles,molecule,library
provisioner:
  name: ansible
  options:
    become: true
scenario:
  name: default
verifier:
  name: testinfra
  options:
    sudo: true
